BSRD-106 Publish dump-bag
camptocamp/odoo-dump-bag pull request #11
Opened 2018-11-23 15:49 UTC by leemannd

*TODO*
- [x] Add/Improve the docs (adding use cases,...)
- [x] Update License to AGLP
- [x] Check if there is anything private

2019-01-25 06:24 UTC, simahawk requested changes
pls review the readme, contains links to internal stuff.
Plus, it misses and important thing; what the hell is this tool for? The main description ;)

2019-01-25 08:39 UTC, tschanzt approved these changes
looks good from what i see.

2019-02-06 14:38 UTC, asaunier approved these changes

2019-07-02 14:38 UTC, vrenaville approved these changes

2019-07-03 13:09 UTC, simahawk approved these changes

2019-09-05 16:33 UTC, yvaucher approved these changes

2019-09-24 09:04 UTC, guewen approved these changes

2019-09-24 09:04 UTC, merged